#e2.1Drawpython.py
from random import*
import turtle
turtle.setup(650,350,200,200)
turtle.penup()
turtle.fd(-250)
turtle.pendown()
turtle.pendown()
turtle.pensize(25)
turtle.pencolor("purple")
turtle.seth(-40)
turtle.circle(40,80)
turtle.pencolor("red")
turtle.circle(-40,80)
turtle.pencolor("blue")
turtle.circle(40,80)
turtle.pencolor("orange")
turtle.circle(-40,80)
turtle.pencolor("green")
turtle.circle(40,80)
turtle.pencolor("yellow")
turtle.circle(-40,80)
turtle.pencolor("pink")
turtle.circle(-16,180)
turtle.pencolor("black")
turtle.circle(-16,180)
turtle.fd(40)
turtle.backward(6)
turtle.pencolor("white")
turtle.pensize(2)
turtle.circle(2,360)
turtle.circle(6,360)
 
