
import turtle as t
t.setup(1250,650,20,20)
t.color('black','red')

t.penup()
t.goto(-300,-200)
t.pensize (20)
t.seth(90)
t.pendown()
t.fd(400)
t.penup()
t.pensize(10)
t.pendown()
t.begin_fill()
t.seth(0)
t.fd(100)
t.seth(-40)
t.circle(150,80)
t.circle(-150,80)
t.seth(-90)
t.fd(300)
t.seth(140)
t.circle(150,80)
t.circle(-150,80)
t.seth(180)
t.fd(100)
t.end_fill()
t.penup()
t.goto(-300,80)
t.pendown()
t.seth(0)
t.pencolor("yellow")
t.fillcolor("yellow")
t.begin_fill()
for i in range(5):
    t.forward(200)
    t.right(144)        
t.end_fill()
t.penup()
t.goto(-100,140)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
for i in range(5):
    t.forward(50)
    t.right(144)        
t.end_fill()
t.penup()
t.goto(-40,80)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
for i in range(5):
    t.forward(50)
    t.right(144)        
t.end_fill()
t.penup()
t.goto(-100,-60)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
for i in range(5):
    t.forward(50)
    t.right(144)        
t.end_fill()
t.penup()
t.goto(-60,0)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
for i in range(5):
    t.forward(50)
    t.right(144)        
t.end_fill()
